dist: trusty
sudo: required
language: go
go: '1.10'
services:
  - docker
install:
  - make setup
script:
  - make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
